import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
import { FBXLoader } from 'https://cdn.jsdelivr.net/npm/three@0.160.1/examples/jsm/loaders/FBXLoader.js';

const $ = id => document.getElementById(id);
const ui = Object.fromEntries(['coins','cosmic','level','xpLabel','xpFill','treats','power','powerName','multiplier','regionName','objectiveTitle','objectiveText','objectiveProgress','objectiveFill','drawerCoins','upgradeList','missionList','toast','eventBanner','eventText','startScreen','barkCooldown','weatherIcon'].map(k=>[k,$(k)]));
const state={running:false,coins:250,cosmic:0,treats:0,xp:0,level:1,power:1,destroyed:0,birds:0,treasures:0,multiplier:1,time:0,region:'Praia do Petisco',upgrades:{speed:1,force:1,magnet:0,luck:0,dig:0},missions:[
  {id:'snacks',title:'Faro de campeão',text:'Encontre petiscos escondidos.',goal:20,value:0,reward:180},
  {id:'smash',title:'Pequeno grande caos',text:'Destrua objetos pelo calçadão.',goal:18,value:0,reward:250},
  {id:'dig',title:'Tesouro de areia',text:'Desenterre pontos suspeitos.',goal:3,value:0,reward:150},
  {id:'birds',title:'Pombos em pânico',text:'Faça pombos levantarem voo.',goal:8,value:0,reward:120}
]};
const upgrades=[
  {id:'speed',icon:'⚡',title:'Patas Velozes',desc:'Corre mais rápido pelo mapa.',base:75},
  {id:'force',icon:'✹',title:'Latido Poderoso',desc:'Quebra coisas cada vez maiores.',base:110},
  {id:'magnet',icon:'⌁',title:'Ímã de Petiscos',desc:'Atrai petiscos próximos.',base:95},
  {id:'luck',icon:'✦',title:'Sorte Salsicha',desc:'Mais moedas e itens dourados.',base:130},
  {id:'dig',icon:'⌄',title:'Escavação Turbo',desc:'Desenterra tesouros muito mais rápido.',base:100}
];
let scene,camera,renderer,dog,blaster,ocean,toastTimer,shake=0,lastEvent=0,dogMixer,audioContext,musicTimer,musicStep=0,musicElement,melzinhaBoss;
const clock=new THREE.Clock(),keys={},collectibles=[],objects=[],digSpots=[],birdList=[],particles=[],projectiles=[],patrolCars=[],chaosBots=[],climbPoints=[];
const player={pos:new THREE.Vector3(-10,0,6),velocity:new THREE.Vector3(),moveVelocity:new THREE.Vector3(),dir:0,cameraYaw:0,cameraPitch:.08,onGround:true,groundY:0,climbTarget:null,action:'idle',actionUntil:0,dash:0,dashCooldown:0,aiming:false,fireCooldown:0};
const dogParts={},camPos=new THREE.Vector3(),camLook=new THREE.Vector3();

function material(color,rough=.75){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:0});}
function mesh(geo,mat,x=0,y=0,z=0,scale=1,parent=scene){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);typeof scale==='number'?m.scale.setScalar(scale):m.scale.copy(scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function makeCanvasTexture(text){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='#fdf3be';x.textAlign='center';x.font='900 42px Nunito';text.split('\n').forEach((line,i)=>x.fillText(line,256,58+i*51));const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function initAudio(){if(!audioContext){const Audio=window.AudioContext||window.webkitAudioContext;if(Audio)audioContext=new Audio();}audioContext?.resume?.();}
function playSound(type){if(!audioContext)return;const settings={collect:[780,.1,'sine'],bark:[105,.2,'sawtooth'],shot:[440,.07,'square'],dash:[210,.12,'triangle'],dig:[160,.11,'triangle'],crash:[90,.18,'sawtooth'],bot:[260,.16,'square']}[type]||[300,.08,'sine'],osc=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;osc.type=settings[2];osc.frequency.setValueAtTime(settings[0],now);osc.frequency.exponentialRampToValueAtTime(Math.max(45,settings[0]*.45),now+settings[1]);gain.gain.setValueAtTime(.055,now);gain.gain.exponentialRampToValueAtTime(.001,now+settings[1]);osc.connect(gain).connect(audioContext.destination);osc.start(now);osc.stop(now+settings[1]);}
function startMusic(){if(!musicElement){musicElement=new Audio('assets/audio/trilha-morro.mp3');musicElement.loop=true;musicElement.volume=.24;musicElement.addEventListener('error',()=>startFallbackMusic(),{once:true});}musicElement.play().catch(()=>startFallbackMusic());}
function startFallbackMusic(){if(!audioContext||musicTimer)return;const notes=[220,262,330,294,247,294,370,330];musicTimer=setInterval(()=>{if(!state.running||!audioContext)return;const osc=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;osc.type='triangle';osc.frequency.setValueAtTime(notes[musicStep++%notes.length],now);gain.gain.setValueAtTime(.018,now);gain.gain.exponentialRampToValueAtTime(.001,now+.42);osc.connect(gain).connect(audioContext.destination);osc.start(now);osc.stop(now+.44);},430);}
function setup(){
  renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
  scene=new THREE.Scene();scene.background=new THREE.Color('#77c9e5');scene.fog=new THREE.Fog('#77c9e5',42,145);camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,250);camera.position.set(-2,7,14);scene.add(camera);
  scene.add(new THREE.HemisphereLight('#d9f4ff','#5d8657',2.1));const sun=new THREE.DirectionalLight('#fff3c4',3);sun.position.set(-42,62,28);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;scene.add(sun);
  makeWorld();makeDog();makeBlaster();bind();updateUI();resize();animate();
}
function makeWorld(){
  const ground=mesh(new THREE.PlaneGeometry(175,145),material('#e8c974'),17,0,3);ground.rotation.x=-Math.PI/2;
  ocean=mesh(new THREE.PlaneGeometry(150,150),material('#41abd0',.35),-67,-.12,0);ocean.rotation.x=-Math.PI/2;ocean.receiveShadow=false;
  const boardwalk=mesh(new THREE.BoxGeometry(38,.12,140),material('#d9d8c5'),-3,.05,2);boardwalk.castShadow=false;const road=mesh(new THREE.BoxGeometry(23,.15,120),material('#69767a'),38,.06,0);road.castShadow=false;
  for(let z=-54;z<60;z+=7){const stripe=mesh(new THREE.BoxGeometry(.32,.02,3.4),material('#eee3ac'),38,.15,z);stripe.castShadow=false;}
  for(let i=0;i<40;i++){const z=-68+(i%14)*10+(i%2)*2,foam=mesh(new THREE.TorusGeometry(1.2,.08,6,12),material('#dffbfa'),-34-(i%3)*10,.035,z);foam.rotation.x=-Math.PI/2;foam.scale.x=1.8;foam.castShadow=false;}
  for(let z=-52;z<64;z+=16){umbrella(-24,z,z%32===0?'#ff7560':'#f7c958');palm(-17,z+5,1);palm(10,z-5,.82);}
  const cols=['#f38b66','#f8c36b','#78b6c9','#d98faf'];for(let z=-52,i=0;z<61;z+=17,i++){building(52,z,9+(i%3)*2,cols[i%4]);building(66,z+4,8+(i%4),cols[(i+1)%4]);}streetDetails();
  mountain(83,0,14,'#4a8560');mountain(94,-17,20,'#3e7657');mountain(91,25,18,'#548d63');hillsideNeighborhood();makeMelzinha();makePatrolCar(34,-46,1,.8);makePatrolCar(43,30,-1,1.05);gate(18,-4,'RUAS DA\nCONFUSÃO',30);gate(42,24,'CENTRO DO\nCAOS',60);gate(65,47,'MORRO DO\nMISTÉRIO',90);statue(-4,45);npc(-9,-25,'#d5644f');npc(8,32,'#e5c767');npc(42,-32,'#6eb0d0');spawnContent();
}
function umbrella(x,z,color){mesh(new THREE.CylinderGeometry(.08,.08,2.2,8),material('#80513d'),x,1.1,z);const top=mesh(new THREE.ConeGeometry(2.1,.7,16),material(color),x,2.3,z);top.scale.z=.85;}
function palm(x,z,s=1){const trunk=mesh(new THREE.CylinderGeometry(.23,.38,5*s,8),material('#9b603e'),x,2.5*s,z);trunk.rotation.z=.09;for(let i=0;i<7;i++){const leaf=mesh(new THREE.SphereGeometry(.78*s,8,6),material('#418961'),x+Math.cos(i)*1.05*s,5*s,z+Math.sin(i)*1.05*s,new THREE.Vector3(1.6,.28,.58));leaf.rotation.y=i*.9;}}
function building(x,z,h,color){mesh(new THREE.BoxGeometry(7,h,9),material(color),x,h/2,z);mesh(new THREE.BoxGeometry(7.4,.4,9.4),material('#e7f0dc'),x,h+.15,z);for(let a=0;a<2;a++)for(let b=0;b<2;b++){const w=mesh(new THREE.BoxGeometry(1.3,1.3,.08),material('#2f6381'),x-1.8+a*3.4,h*.45+b*2.2,z-4.55);w.castShadow=false;}}
function mountain(x,z,s,color){const m=mesh(new THREE.ConeGeometry(s*.75,s*1.8,8),material(color),x,s*.8,z);m.scale.z=.8;m.castShadow=false;for(let i=0;i<4;i++)palm(x-4+i*3,z+3+(i%2)*4,.65);}
function streetDetails(){const pole=material('#314b58'),lamp=new THREE.MeshStandardMaterial({color:'#fff2ae',emissive:'#ffd85d',emissiveIntensity:1.15});for(let z=-48;z<56;z+=14){mesh(new THREE.CylinderGeometry(.12,.16,5.8,8),pole,26,2.9,z);mesh(new THREE.CylinderGeometry(.12,.16,5.8,8),pole,50,2.9,z+6);mesh(new THREE.SphereGeometry(.27,10,8),lamp,26,5.8,z,1);mesh(new THREE.SphereGeometry(.27,10,8),lamp,50,5.8,z+6,1);}for(let z=-44;z<54;z+=18){const stall=new THREE.Group();stall.position.set(17,0,z);mesh(new THREE.BoxGeometry(2.6,1.4,1.5),material(z%36?'#edb955':'#d86655'),0,.7,0,1,stall);mesh(new THREE.ConeGeometry(1.65,.58,4),material('#f7e6b6'),0,1.7,0,1,stall);scene.add(stall);}for(let i=0;i<9;i++){const cone=mesh(new THREE.ConeGeometry(.22,.55,10),material('#ff7d47'),31+i%2*13,.3,-38+Math.floor(i/2)*12);cone.castShadow=false;}}
function hillsideNeighborhood(){const palette=['#ed765e','#f5be5c','#69a9b5','#d87b9a','#8cac69','#ef9361'];for(let row=0;row<4;row++){const elevation=row*1.28;for(let col=0;col<5;col++){const x=68+col*5.1+(row%2)*2.4,z=-18+row*10+(col%2)*1.3;hillsideHouse(x,z,elevation,palette[(row*3+col)%palette.length]);}const landing=mesh(new THREE.BoxGeometry(31,.4,5),material(row%2?'#81755e':'#9b8e69'),78,elevation-.25,-17+row*10);landing.castShadow=false;makeClimbPoint(65,-17+row*10,elevation,2.6);}[[58,-24,.45],[61,-21,1.05],[64,-19,1.7],[67,-17,2.4],[70,-15,3.2],[74,-12,4.1],[79,-8,5]].forEach(([x,z,h])=>makeClimbPoint(x,z,h,2.1));for(let i=0;i<24;i++){const cable=mesh(new THREE.CylinderGeometry(.018,.018,7,6),material('#263b47'),65+(i%4)*8,4+(i%3)*1,-25+Math.floor(i/4)*9);cable.rotation.z=Math.PI/2;}}
function makeClimbPoint(x,z,height,radius){const step=mesh(new THREE.CylinderGeometry(radius*.72,radius,Math.max(.22,height+.12),8),material('#937b5e'),x,Math.max(.11,height/2),z);step.castShadow=false;climbPoints.push({x,z,height,radius});}
function hillsideHouse(x,z,y,color){const g=new THREE.Group();g.position.set(x,y,z);mesh(new THREE.BoxGeometry(4.3,3.3,4),material(color),0,1.65,0,1,g);mesh(new THREE.ConeGeometry(3.3,1.4,4),material('#d9e0d3'),0,4,0,1,g);const door=mesh(new THREE.BoxGeometry(.9,1.5,.08),material('#6b4a3c'),0,.76,-2.05,1,g);door.castShadow=false;[-1.2,1.2].forEach(px=>{const window=mesh(new THREE.BoxGeometry(.72,.7,.08),material('#315f79'),px,2.25,-2.06,1,g);window.castShadow=false;});const tank=mesh(new THREE.CylinderGeometry(.54,.64,.9,10),material('#467a88'),1.25,4.7,.45,1,g);tank.castShadow=false;scene.add(g);}
function makePatrolCar(x,z,direction,speed){const g=new THREE.Group(),loader=new THREE.TextureLoader(),bodyTexture=loader.load('assets/police/Crown_Vic_Body_Color.png'),roughness=loader.load('assets/police/Crown_Vic_Body_Roughnes.png');bodyTexture.colorSpace=THREE.SRGBColorSpace;const blue=new THREE.MeshStandardMaterial({map:bodyTexture,roughnessMap:roughness,roughness:.52,metalness:.15}),white=material('#edf6f2',.36),tire=material('#171d25'),chrome=new THREE.MeshStandardMaterial({color:'#c7e1e4',metalness:.82,roughness:.22}),glass=new THREE.MeshStandardMaterial({color:'#255f7e',roughness:.15,metalness:.15,transparent:true,opacity:.82});g.position.set(x,.28,z);mesh(new THREE.BoxGeometry(2.25,.52,4.45),blue,0,.42,0,1,g);mesh(new THREE.BoxGeometry(1.88,.62,2.05),white,0,.94,.08,1,g);mesh(new THREE.BoxGeometry(1.56,.38,1.42),glass,0,1.24,.08,1,g);mesh(new THREE.BoxGeometry(2.3,.14,.24),chrome,0,.43,-2.27,1,g);mesh(new THREE.BoxGeometry(2.3,.14,.24),chrome,0,.43,2.27,1,g);mesh(new THREE.BoxGeometry(1.15,.09,.12),chrome,0,.6,-2.42,1,g);[-.99,.99].forEach(px=>[-1.38,1.38].forEach(pz=>{const wheel=mesh(new THREE.CylinderGeometry(.36,.36,.25,12),tire,px,.3,pz,1,g);wheel.rotation.z=Math.PI/2;const hub=mesh(new THREE.CylinderGeometry(.16,.16,.26,10),chrome,px,.3,pz,1,g);hub.rotation.z=Math.PI/2;}));const red=new THREE.MeshStandardMaterial({color:'#ff4d56',emissive:'#ff232f',emissiveIntensity:1.8}),cyan=new THREE.MeshStandardMaterial({color:'#58d8ff',emissive:'#1399ff',emissiveIntensity:1.8}),headlight=new THREE.MeshStandardMaterial({color:'#fff7bd',emissive:'#ffe477',emissiveIntensity:1.1});const left=mesh(new THREE.BoxGeometry(.52,.17,.36),red,-.39,1.55,.02,1,g),right=mesh(new THREE.BoxGeometry(.52,.17,.36),cyan,.39,1.55,.02,1,g);[-.67,.67].forEach(px=>mesh(new THREE.BoxGeometry(.34,.18,.09),headlight,px,.63,-2.3,1,g));g.rotation.y=direction>0?0:Math.PI;scene.add(g);patrolCars.push({g,direction,speed,lights:[left,right]});}
function makeChaosBot(x,z,seed){const g=new THREE.Group(),bodyMat=material('#4b445f',.35),armor=material('#d96551',.4),eye=new THREE.MeshStandardMaterial({color:'#fff1a0',emissive:'#ffb13e',emissiveIntensity:1.4});g.position.set(x,.65,z);mesh(new THREE.SphereGeometry(.55,12,10),bodyMat,0,.65,0,1,g);mesh(new THREE.BoxGeometry(.82,.35,.48),armor,0,.62,.05,1,g);mesh(new THREE.SphereGeometry(.28,10,8),bodyMat,0,1.35,-.08,1,g);mesh(new THREE.SphereGeometry(.07,8,6),eye,-.1,1.37,-.33,1,g);mesh(new THREE.SphereGeometry(.07,8,6),eye,.1,1.37,-.33,1,g);[-.45,.45].forEach(px=>mesh(new THREE.CapsuleGeometry(.08,.42,4,6),bodyMat,px,.2,0,1,g));scene.add(g);chaosBots.push({g,home:new THREE.Vector3(x,.65,z),seed,health:2,disabled:false,hitCooldown:0});}
function makeMelzinha(){const g=new THREE.Group(),fallback=new THREE.Group();g.position.set(82,5,-8);g.add(fallback);const fur=material('#d8a66c'),white=material('#f7e5c4'),brown=material('#70452d');mesh(new THREE.CapsuleGeometry(.72,1.5,7,12),fur,0,.76,0,new THREE.Vector3(1,1,1.35),fallback).rotation.z=Math.PI/2;mesh(new THREE.SphereGeometry(.72,14,10),white,0,1.1,-1.2,1,fallback);[-.4,.4].forEach((x,i)=>{const ear=mesh(new THREE.CapsuleGeometry(.16,.65,5,8),brown,x*1.5,.92,-.92,1,fallback);ear.rotation.z=i?-.43:.43;});const aura=mesh(new THREE.TorusGeometry(1.9,.06,8,24),new THREE.MeshBasicMaterial({color:'#ffba5f',transparent:true,opacity:.65}),0,.12,0,1,g);aura.rotation.x=-Math.PI/2;aura.castShadow=false;scene.add(g);melzinhaBoss={g,fallback,aura,health:100,maxHealth:100,active:false,defeated:false,phase:'sleep',timer:0,dashDir:new THREE.Vector3(),hitCooldown:0};const texture=new THREE.TextureLoader().load('assets/melzinha/Beagle_texture.png');texture.colorSpace=THREE.SRGBColorSpace;const bossMaterial=new THREE.MeshStandardMaterial({map:texture,roughness:.78});new FBXLoader().load('assets/melzinha/Beagle.fbx',model=>{const raw=new THREE.Box3().setFromObject(model),size=raw.getSize(new THREE.Vector3()),scale=3.2/Math.max(size.x,size.y,size.z);model.scale.setScalar(scale);model.traverse(node=>{if(node.isMesh){node.material=bossMaterial;node.castShadow=true;node.receiveShadow=true;}});model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);model.rotation.y=Math.PI;fallback.visible=false;g.add(model);melzinhaBoss.model=model;},undefined,()=>{});}
function gate(x,z,label,need){const g=new THREE.Group();g.position.set(x,0,z);[-3.3,3.3].forEach(px=>{mesh(new THREE.BoxGeometry(.45,4,.45),material('#3a6d74'),px,2,0,1,g);mesh(new THREE.SphereGeometry(.42,10,8),material('#ffcf5c'),px,4.1,0,1,g);});mesh(new THREE.BoxGeometry(7.7,1.7,.28),material('#173d55'),0,3.5,0,1,g);const face=mesh(new THREE.PlaneGeometry(7.25,1.42),new THREE.MeshBasicMaterial({map:makeCanvasTexture(label+'\n'+need+' PETISCOS'),transparent:true}),0,3.5,.151,1,g);face.castShadow=false;scene.add(g);}
function statue(x,z){const g=new THREE.Group();g.position.set(x,0,z);mesh(new THREE.CylinderGeometry(1.4,1.7,1.1,10),material('#b7d1cc'),0,.55,0,1,g);mesh(new THREE.SphereGeometry(.85,12,8),material('#d5e0d7'),0,1.7,0,1,g);mesh(new THREE.ConeGeometry(.55,1.3,8),material('#d5e0d7'),0,2.6,0,1,g);scene.add(g);}
function npc(x,z,color){const g=new THREE.Group();g.position.set(x,0,z);mesh(new THREE.CylinderGeometry(.28,.34,1.4,8),material(color),0,.7,0,1,g);mesh(new THREE.SphereGeometry(.34,10,8),material('#f3c09d'),0,1.65,0,1,g);scene.add(g);}
function spawnContent(){
  for(let i=0;i<120;i++){let x,z;if(i<30){x=-27+Math.random()*34;z=-56+Math.random()*118;}else if(i<60){x=11+Math.random()*28;z=-55+Math.random()*105;}else if(i<90){x=35+Math.random()*30;z=-52+Math.random()*105;}else{x=60+Math.random()*28;z=-45+Math.random()*86;}treat(x,z,i);}
  for(let i=0;i<72;i++){let x,z;if(i<30){x=-17+Math.random()*28;z=-55+Math.random()*111;}else if(i<52){x=20+Math.random()*29;z=-50+Math.random()*106;}else{x=54+Math.random()*28;z=-40+Math.random()*75;}breakable(x,z,i);}
  for(let i=0;i<12;i++)digSpots.push(digSpot(-21+Math.random()*39,-55+Math.random()*110));for(let i=0;i<20;i++)birdList.push(bird(-11+Math.random()*20,-55+Math.random()*110));[[49,-15],[57,10],[70,23],[78,-5],[82,37]].forEach(([x,z],i)=>makeChaosBot(x,z,i));
}
function treat(x,z,index){const g=new THREE.Group();g.position.set(x,.6,z);const rare=index%29===0,legendary=index===119,color=legendary?'#c99cff':rare?'#ffd45a':'#f5a761';const body=mesh(new THREE.CylinderGeometry(.38,.38,.25,8),material(color,.45),0,0,0,1,g);body.rotation.x=Math.PI/2;mesh(new THREE.SphereGeometry(.2,8,6),material(color),-.42,0,0,1,g);mesh(new THREE.SphereGeometry(.2,8,6),material(color),.42,0,0,1,g);g.userData={rare,legendary,index,baseY:.6,claimed:false};scene.add(g);collectibles.push(g);return g;}
function breakable(x,z,index){const types=[{name:'lixeira',geo:new THREE.CylinderGeometry(.5,.6,1.25,10),color:'#4c9a87',y:.62},{name:'caixa',geo:new THREE.BoxGeometry(1.05,1.05,1.05),color:'#bf7a43',y:.53},{name:'vaso',geo:new THREE.CylinderGeometry(.45,.34,.85,9),color:'#e26f59',y:.43},{name:'banca',geo:new THREE.BoxGeometry(1.8,1.2,.85),color:'#f0b94e',y:.6},{name:'banco',geo:new THREE.BoxGeometry(1.9,.65,.55),color:'#8c5d3e',y:.35}],v=types[index%types.length],g=new THREE.Group();g.position.set(x,0,z);mesh(v.geo,material(v.color),0,v.y,0,1,g);if(v.name==='vaso')mesh(new THREE.ConeGeometry(.62,1.2,7),material('#4a8b58'),0,1.18,0,1,g);if(v.name==='banca')mesh(new THREE.ConeGeometry(.9,.7,4),material('#ed684e'),0,1.55,0,1,g);g.userData={name:v.name,required:1+Math.floor(index/18),broken:false};scene.add(g);objects.push(g);}
function digSpot(x,z){const r=mesh(new THREE.TorusGeometry(.58,.1,8,12),material('#b78549'),x,.07,z);r.rotation.x=-Math.PI/2;r.userData={dug:false};return r;}
function bird(x,z){const g=new THREE.Group();g.position.set(x,.32,z);mesh(new THREE.SphereGeometry(.19,8,6),material('#566f77'),0,0,0,1,g);const w=mesh(new THREE.ConeGeometry(.28,.6,3),material('#738a8a'),0,.05,0,1,g);w.rotation.z=Math.PI/2;scene.add(g);return {g,home:new THREE.Vector3(x,.32,z),flying:0,phase:Math.random()*6};}
function makeDog(){
  dog=new THREE.Group();dog.position.copy(player.pos);scene.add(dog);const fallback=new THREE.Group();dog.add(fallback);dogParts.fallback=fallback;const fur=material('#a95b35'),dark=material('#69341f'),cream=material('#dfa16d'),black=material('#201a1b');
  dogParts.body=mesh(new THREE.CapsuleGeometry(.62,1.25,7,14),fur,0,.62,0,new THREE.Vector3(1,1,1.55),fallback);dogParts.body.rotation.z=Math.PI/2;dogParts.head=mesh(new THREE.SphereGeometry(.58,16,12),fur,0,.88,-1.05,1,fallback);mesh(new THREE.SphereGeometry(.34,12,8),cream,0,.72,-1.52,new THREE.Vector3(1,.72,1),fallback);mesh(new THREE.SphereGeometry(.12,10,8),black,0,.79,-1.79,1,fallback);
  [-.28,.28].forEach((x,i)=>{mesh(new THREE.SphereGeometry(.075,8,6),black,x,.99,-1.45,1,fallback);const ear=mesh(new THREE.CapsuleGeometry(.14,.5,5,8),dark,x*1.8,.77,-.9,1,fallback);ear.rotation.z=i?-.45:.45;dogParts['ear'+i]=ear;});dogParts.tail=mesh(new THREE.CapsuleGeometry(.1,.72,5,8),fur,0,.8,1.25,1,fallback);dogParts.tail.rotation.x=Math.PI/2.45;dogParts.legs=[];[-.38,.38].forEach(x=>[-.65,.68].forEach(z=>dogParts.legs.push(mesh(new THREE.CapsuleGeometry(.13,.34,5,8),fur,x,.28,z,1,fallback))));const shadow=mesh(new THREE.CircleGeometry(1.2,20),new THREE.MeshBasicMaterial({color:'#204553',transparent:true,opacity:.28}),0,.012,0,1,dog);shadow.rotation.x=-Math.PI/2;shadow.scale.z=1.55;shadow.castShadow=false;loadDachshund(fallback);
}
function loadDachshund(fallback){const textures=new THREE.TextureLoader(),base=textures.load('assets/meyui/dachshunddog3dmodel_basecolor.jpeg');base.colorSpace=THREE.SRGBColorSpace;const dogMaterial=new THREE.MeshStandardMaterial({map:base,normalMap:textures.load('assets/meyui/dachshunddog3dmodel_normal.jpeg'),roughnessMap:textures.load('assets/meyui/dachshunddog3dmodel_roughness.jpeg'),metalnessMap:textures.load('assets/meyui/dachshunddog3dmodel_metallic.jpeg'),roughness:.82,metalness:0});new FBXLoader().load('assets/meyui/dachshund+dog+3d+model.fbx',model=>{const rawBox=new THREE.Box3().setFromObject(model),rawSize=rawBox.getSize(new THREE.Vector3()),scale=2.8/Math.max(rawSize.x,rawSize.z,rawSize.y);model.scale.setScalar(scale);model.traverse(node=>{if(node.isMesh){node.material=dogMaterial;node.castShadow=true;node.receiveShadow=true;}});model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3());model.position.set(-center.x,-box.min.y,-center.z);model.rotation.y=Math.PI/2;fallback.visible=false;dog.add(model);dogParts.imported=model;dogParts.importBaseY=model.position.y;if(model.animations.length){dogMixer=new THREE.AnimationMixer(model);dogMixer.clipAction(model.animations[0]).play();}},undefined,()=>{showToast('O modelo 3D não carregou; usando o Meyui estilizado.');});}
function makeBlaster(){
  blaster=new THREE.Group();const orange=material('#ff8548',.45),mint=material('#62dbc5',.35),cream=material('#fff1b3',.3),dark=material('#244e65');
  mesh(new THREE.BoxGeometry(.24,.2,.64),orange,.03,-.03,-.2,1,blaster);mesh(new THREE.CylinderGeometry(.13,.16,.48,12),mint,.03,.04,-.64,1,blaster).rotation.x=Math.PI/2;mesh(new THREE.CylinderGeometry(.16,.16,.08,12),cream,.03,.04,-.9,1,blaster).rotation.x=Math.PI/2;const grip=mesh(new THREE.BoxGeometry(.18,.34,.15),dark,.03,-.23,.02,1,blaster);grip.rotation.x=-.3;mesh(new THREE.SphereGeometry(.09,10,8),cream,.03,.14,-.28,1,blaster);blaster.position.set(.46,-.42,-.86);blaster.rotation.set(.04,-.13,0);blaster.visible=false;camera.add(blaster);
}
function bind(){
  const gameCanvas=$('game');
  addEventListener('resize',resize);addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','KeyE','KeyQ','KeyF','KeyU','KeyM','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!e.repeat){if(e.code==='KeyE')bark();if(e.code==='KeyQ')sniff();if(e.code==='KeyF')dig();if(e.code==='KeyU')openDrawer('upgradeDrawer');if(e.code==='KeyM')openDrawer('mapDrawer');if(e.code==='Space')jump();if(e.code==='ShiftLeft'||e.code==='ShiftRight')dash();}});addEventListener('keyup',e=>keys[e.code]=false);
  let mouseDrag=null;const rotateCamera=(dx,dy)=>{player.cameraYaw-=dx*.005;player.cameraPitch=THREE.MathUtils.clamp(player.cameraPitch-dy*.004,-.35,.34);};const tryPointerLock=()=>{try{const pending=gameCanvas.requestPointerLock?.();pending?.catch?.(()=>{});}catch(_error){/* O arrasto abaixo mantém a câmera funcional quando pointer lock não existe. */}};
  gameCanvas.addEventListener('contextmenu',e=>e.preventDefault());gameCanvas.addEventListener('pointerdown',e=>{if(!state.running)return;initAudio();mouseDrag={x:e.clientX,y:e.clientY};tryPointerLock();if(e.button===2){player.aiming=true;e.preventDefault();}if(e.button===0&&player.aiming)shoot();try{gameCanvas.setPointerCapture?.(e.pointerId);}catch(_error){/* Alguns navegadores em prévia não expõem o ponteiro para captura. */}});gameCanvas.addEventListener('pointermove',e=>{if(!state.running||document.pointerLockElement===gameCanvas)return;if(mouseDrag){rotateCamera(e.clientX-mouseDrag.x,e.clientY-mouseDrag.y);mouseDrag={x:e.clientX,y:e.clientY};}});addEventListener('pointerup',e=>{mouseDrag=null;if(e.button===2)player.aiming=false;});document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==gameCanvas)player.aiming=false;});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===gameCanvas&&state.running)rotateCamera(e.movementX,e.movementY);});
  $('startButton').onclick=()=>{initAudio();startMusic();state.running=true;ui.startScreen.classList.add('hide');showToast('Meyui Beuyi está com fome. Encontre petiscos!');};$('barkButton').onclick=()=>{initAudio();bark();};$('sniffButton').onclick=()=>{initAudio();sniff();};$('digButton').onclick=()=>{initAudio();dig();};$('upgradeButton').onclick=()=>openDrawer('upgradeDrawer');$('missionButton').onclick=()=>openDrawer('missionDrawer');$('mapButton').onclick=()=>openDrawer('mapDrawer');$('mobileBark').onclick=()=>{initAudio();bark();};$('mobileJump').onclick=jump;$('prestigeButton').onclick=prestige;document.querySelectorAll('.close-button').forEach(b=>b.onclick=()=>$(b.dataset.close).hidden=true);
  const stick=$('joystick'),knob=stick.querySelector('i');let touch=null;const follow=e=>{const p=[...e.touches].find(t=>t.identifier===touch);if(!p)return;const r=stick.getBoundingClientRect(),dx=p.clientX-r.left-r.width/2,dy=p.clientY-r.top-r.height/2,l=Math.min(28,Math.hypot(dx,dy)),n=Math.hypot(dx,dy)||1;keys.touchX=dx/n*l/28;keys.touchY=dy/n*l/28;knob.style.transform=`translate(${keys.touchX*25}px,${keys.touchY*25}px)`;};stick.addEventListener('touchstart',e=>{touch=e.changedTouches[0].identifier;follow(e);e.preventDefault()},{passive:false});stick.addEventListener('touchmove',follow,{passive:true});stick.addEventListener('touchend',()=>{touch=null;keys.touchX=keys.touchY=0;knob.style.transform='';});
}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(state.running){state.time+=dt;dogMixer?.update(dt);playerUpdate(dt);worldUpdate(dt);cameraUpdate(dt);if(Math.floor(state.time)!==Math.floor(state.time-dt))updateUI();}renderer.render(scene,camera);}
function playerUpdate(dt){
  const forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)-(keys.touchY||0),right=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+(keys.touchX||0);let x=Math.sin(player.cameraYaw)*forward+Math.cos(player.cameraYaw)*right,z=Math.cos(player.cameraYaw)*forward-Math.sin(player.cameraYaw)*right,len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}const inputMoving=len>.08,baseSpeed=5.05+state.upgrades.speed*.42,speed=baseSpeed*(player.dash>0?2.2:1),desired=new THREE.Vector3(x*speed,0,z*speed),acceleration=inputMoving?(player.dash>0?22:15):10;player.moveVelocity.lerp(desired,1-Math.exp(-dt*acceleration));const moving=player.moveVelocity.lengthSq()>.18;if(moving){const target=Math.atan2(player.moveVelocity.x,player.moveVelocity.z),delta=THREE.MathUtils.euclideanModulo(target-player.dir+Math.PI,Math.PI*2)-Math.PI;player.dir+=delta*Math.min(1,dt*(player.dash>0?24:15));}player.pos.addScaledVector(player.moveVelocity,dt);player.dash=Math.max(0,player.dash-dt);player.dashCooldown=Math.max(0,player.dashCooldown-dt);player.fireCooldown=Math.max(0,player.fireCooldown-dt);
  player.pos.x=Math.max(-31,Math.min(88,player.pos.x));player.pos.z=Math.max(-63,Math.min(67,player.pos.z));if(player.onGround&&player.groundY>0&&!climbPoints.some(p=>Math.hypot(player.pos.x-p.x,player.pos.z-p.z)<p.radius+.18&&Math.abs(p.height-player.groundY)<.25)){player.onGround=false;player.velocity.y=-.3;}if(!player.onGround){player.velocity.y-=15*dt;player.pos.y+=player.velocity.y*dt;const landing=player.climbTarget;if(landing&&player.velocity.y<=0&&Math.hypot(player.pos.x-landing.x,player.pos.z-landing.z)<landing.radius+.65&&player.pos.y<=landing.height){player.pos.y=landing.height;player.groundY=landing.height;player.onGround=true;player.climbTarget=null;dust(player.pos,5,'#e0bd75');}else if(player.pos.y<=0){player.pos.y=0;player.groundY=0;player.onGround=true;player.climbTarget=null;dust(player.pos,4,'#e0bd75');}}
  dog.position.copy(player.pos);dog.rotation.y=player.dir+Math.PI;const gait=moving?Math.sin(state.time*speed*3.3):Math.sin(state.time*2)*.05;dogParts.body.position.y=.62+(moving?Math.abs(gait)*.04:0);dogParts.legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(state.time*speed*3.3+(i%2)*Math.PI)*.65:0);dogParts.tail.rotation.z=Math.sin(state.time*(moving?11:4))*.35;dogParts.ear0.rotation.x=Math.sin(state.time*7)*.11;dogParts.ear1.rotation.x=-Math.sin(state.time*7)*.11;dogParts.head.scale.setScalar(player.action==='bark'?1.12:1);if(dogParts.imported){dogParts.imported.position.y=dogParts.importBaseY+(moving?Math.abs(gait)*.035:0);dogParts.imported.rotation.z=moving?gait*.035:0;}if(player.actionUntil>0)player.actionUntil-=dt;else player.action='idle';
  collectibles.forEach(c=>{if(c.userData.claimed)return;c.rotation.y+=dt*2;c.position.y=c.userData.baseY+Math.sin(state.time*3+c.userData.index)*.11;const d=dist(c.position,player.pos),radius=1.75+state.upgrades.magnet*.46;if(d<radius){if(state.upgrades.magnet&&d>.18)c.position.lerp(player.pos,.12+state.upgrades.magnet*.025);if(d<1.48)collect(c);}});
}
function worldUpdate(dt){patrolCars.forEach(car=>{car.g.position.z+=car.direction*car.speed*dt;if(car.g.position.z>57||car.g.position.z<-57){car.direction*=-1;car.g.rotation.y=car.direction>0?0:Math.PI;}car.lights.forEach((light,i)=>light.material.emissiveIntensity=(Math.floor(state.time*8+i)%2?1.8:.2));});chaosBots.forEach(bot=>{if(bot.disabled)return;bot.g.position.x=bot.home.x+Math.sin(state.time*1.1+bot.seed)*.7;bot.g.position.z=bot.home.z+Math.cos(state.time*.9+bot.seed)*.7;if(dist(bot.g.position,player.pos)<8){bot.g.lookAt(player.pos.x,bot.g.position.y,player.pos.z);if(bot.hitCooldown<=0&&dist(bot.g.position,player.pos)<2.1){bot.hitCooldown=1.5;shake=.12;player.moveVelocity.multiplyScalar(-.45);showToast('Drone de confete te empurrou!');}}bot.hitCooldown=Math.max(0,bot.hitCooldown-dt);});updateBoss(dt);birdList.forEach(b=>{if(b.flying>0){b.flying-=dt;b.g.position.y+=dt*3;b.g.position.x+=Math.sin(b.phase+state.time*2)*dt*4;b.g.position.z+=dt*6;if(b.flying<=0){b.g.position.copy(b.home);b.g.position.y=.32;}}else b.g.position.y=.32+Math.sin(state.time*3+b.phase)*.05;});for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.mesh.position.addScaledVector(p.dir,p.speed*dt);objects.forEach(o=>{if(!o.userData.broken&&p.life>0&&dist(o.position,p.mesh.position)<1.05){if(state.power>=o.userData.required)destroy(o);else dust(p.mesh.position,4,'#ffcb67');p.life=0;}});chaosBots.forEach(bot=>{if(!bot.disabled&&p.life>0&&p.mesh.position.distanceTo(bot.g.position)<.95){disableBot(bot,1);p.life=0;}});if(melzinhaBoss?.active&&!melzinhaBoss.defeated&&p.life>0&&p.mesh.position.distanceTo(melzinhaBoss.g.position)<1.6){damageBoss(7);p.life=0;}if(p.life<=0){scene.remove(p.mesh);projectiles.splice(i,1);}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.mesh.position.addScaledVector(p.vel,dt);p.vel.y-=8*dt;p.mesh.scale.setScalar(Math.max(0,p.life/p.max));p.mesh.material.opacity=Math.max(0,p.life/p.max);if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1);}}if(state.time-lastEvent>45&&state.time>10){lastEvent=state.time;event();}}
function disableBot(bot,amount){if(bot.disabled)return;bot.health-=amount;dust(bot.g.position,9,'#71e5d1');playSound('bot');if(bot.health<=0){bot.disabled=true;bot.g.rotation.z=Math.PI/2;coins(55);xp(25);showToast('Drone de confete desativado!');}}
function updateBoss(dt){const boss=melzinhaBoss;if(!boss)return;boss.aura.rotation.z+=dt*1.7;if(boss.defeated)return;const distance=dist(boss.g.position,player.pos);if(!boss.active){if(state.treats>=90&&distance<10){boss.active=true;boss.phase='telegraph';boss.timer=1.2;$('bossHud').hidden=false;showToast('MELZINHA acordou! Esquive das investidas.');}return;}boss.g.lookAt(player.pos.x,boss.g.position.y,player.pos.z);boss.hitCooldown=Math.max(0,boss.hitCooldown-dt);if(boss.phase==='telegraph'){boss.timer-=dt;boss.aura.scale.setScalar(1+Math.sin(state.time*16)*.22);if(boss.timer<=0){boss.phase='dash';boss.timer=.7;boss.dashDir.set(player.pos.x-boss.g.position.x,0,player.pos.z-boss.g.position.z).normalize();playSound('bark');}}else if(boss.phase==='dash'){boss.g.position.addScaledVector(boss.dashDir,10.5*dt);if(distance<1.65&&boss.hitCooldown<=0){boss.hitCooldown=.9;player.moveVelocity.addScaledVector(boss.dashDir,9);shake=.26;showToast('Investida da Melzinha! Dê dash para escapar.');}boss.timer-=dt;if(boss.timer<=0){boss.phase='recover';boss.timer=.85;}}else{boss.timer-=dt;if(boss.timer<=0){boss.phase='telegraph';boss.timer=.72;}}}
function damageBoss(amount){const boss=melzinhaBoss;if(!boss||boss.defeated)return;boss.health=Math.max(0,boss.health-amount);$('bossFill').style.width=`${boss.health/boss.maxHealth*100}%`;dust(boss.g.position,8,'#ffb95f');playSound('bot');if(boss.health===0){boss.defeated=true;boss.active=false;$('bossHud').hidden=true;coins(1200);xp(300);showToast('Melzinha foi convencida pelo petisco lendário! Vitória no Morro.');}}
function cameraUpdate(dt){const f=new THREE.Vector3(Math.sin(player.cameraYaw),0,Math.cos(player.cameraYaw));if(player.aiming){const eye=player.pos.clone().addScaledVector(f,.7);eye.y=1.05;camPos.lerp(eye,1-Math.exp(-dt*18));camLook.copy(eye).addScaledVector(f,28);camLook.y+=Math.sin(player.cameraPitch)*28;camera.fov=72;blaster.visible=true;}else{const behind=player.pos.clone().addScaledVector(f,-8.2);behind.y=5.3+player.cameraPitch*5;camPos.lerp(behind,1-Math.exp(-dt*6));camLook.lerp(new THREE.Vector3(player.pos.x+f.x*1.1,1.05,player.pos.z+f.z*1.1),1-Math.exp(-dt*8));camera.fov=58;blaster.visible=false;}camera.position.copy(camPos);camera.position.x+=Math.sin(state.time*28)*shake;camera.position.y+=Math.cos(state.time*31)*shake;shake=Math.max(0,shake-dt*.8);camera.lookAt(camLook);camera.updateProjectionMatrix();document.querySelector('.game-shell').classList.toggle('aiming',player.aiming);}
function jump(){if(!state.running||!player.onGround)return;const target=climbPoints.filter(p=>p.height>player.groundY+.12&&p.height<=player.groundY+2.35&&Math.hypot(player.pos.x-p.x,player.pos.z-p.z)<p.radius+1.8).sort((a,b)=>a.height-b.height)[0];player.onGround=false;player.climbTarget=target||null;player.velocity.y=target?10.4:9.2;player.action='jump';player.actionUntil=.42;playSound('dash');}
function dash(){if(!state.running||player.dashCooldown>0||player.moveVelocity.lengthSq()<.6)return;player.dash=.34;player.dashCooldown=1.05;player.action='dash';player.actionUntil=.28;dust(player.pos,7,'#fff1be');playSound('dash');}
function bark(){if(!state.running||ui.barkCooldown.style.display==='block')return;player.action='bark';player.actionUntil=.35;shake=.24;playSound('bark');ui.barkCooldown.style.display='block';ui.barkCooldown.animate([{transform:'scaleY(1)'},{transform:'scaleY(0)'}],{duration:1400,easing:'linear'});setTimeout(()=>ui.barkCooldown.style.display='none',1400);shockwave(player.pos);let hits=0;objects.forEach(o=>{if(!o.userData.broken&&dist(o.position,player.pos)<3.2+state.upgrades.force*.22&&state.power>=o.userData.required){destroy(o);hits++;}});chaosBots.forEach(bot=>{if(!bot.disabled&&dist(bot.g.position,player.pos)<3.4)disableBot(bot,1);});if(melzinhaBoss?.active&&!melzinhaBoss.defeated&&dist(melzinhaBoss.g.position,player.pos)<3.8)damageBoss(4);birdList.forEach(b=>{if(b.flying<=0&&dist(b.g.position,player.pos)<4){b.flying=2.5;state.birds++;}});if(!hits)showToast('AUUU! Nada frágil o suficiente por perto.');}
function shoot(){if(!state.running||!player.aiming||player.fireCooldown>0)return;player.fireCooldown=.16;player.action='shoot';player.actionUntil=.12;shake=.06;playSound('shot');const dir=new THREE.Vector3();camera.getWorldDirection(dir);const origin=camera.position.clone().addScaledVector(dir,.9);const pellet=mesh(new THREE.SphereGeometry(.105,10,8),new THREE.MeshBasicMaterial({color:'#ffe477'}),origin.x,origin.y,origin.z);pellet.castShadow=false;projectiles.push({mesh:pellet,dir,speed:34,life:1.2});dust(origin,4,'#fff0ad');}
function sniff(){if(!state.running)return;player.action='sniff';player.actionUntil=.6;playSound('collect');const near=collectibles.filter(c=>!c.userData.claimed).sort((a,b)=>a.position.distanceToSquared(player.pos)-b.position.distanceToSquared(player.pos)).slice(0,5);near.forEach(c=>{const r=mesh(new THREE.TorusGeometry(.7,.045,8,20),material('#ffe168'),c.position.x,.12,c.position.z);r.rotation.x=-Math.PI/2;r.castShadow=false;const start=performance.now();const go=t=>{const p=Math.min(1,(t-start)/1350);r.scale.setScalar(1+p*2);r.material.opacity=1-p;if(p<1)requestAnimationFrame(go);else scene.remove(r);};requestAnimationFrame(go);});showToast(near.length?'O focinho aponta para petiscos brilhantes!':'Seu focinho diz: missão cumprida!');}
function dig(){if(!state.running)return;const near=digSpots.find(d=>!d.userData.dug&&dist(d.position,player.pos)<2);if(!near){showToast('Procure um círculo escuro na areia para escavar.');return;}near.userData.dug=true;near.material.color.set('#6e4c32');player.action='dig';player.actionUntil=.7;playSound('dig');state.treasures++;coins(70+state.upgrades.dig*22);dust(near.position,11,'#b5854c');const bonus=treat(near.position.x+.6,near.position.z,1000+state.treasures);bonus.userData.baseY=.6;showToast('Tesouro desenterrado! + moedas e um petisco.');progress();}
function collect(c){if(c.userData.claimed)return;c.userData.claimed=true;state.treats++;const value=(c.userData.legendary?100:c.userData.rare?35:10)*(1+state.upgrades.luck*.12)*state.multiplier;coins(Math.round(value));xp(c.userData.legendary?100:c.userData.rare?35:12);state.missions[0].value++;playSound('collect');dust(c.position,8,c.userData.legendary?'#d1a7ff':'#ffd764');scene.remove(c);if(c.userData.rare)showToast(c.userData.legendary?'PETISCO LENDÁRIO! Que faro.':'Petisco dourado! Que brilho.');progress();}
function destroy(o){o.userData.broken=true;state.destroyed++;state.missions[1].value++;coins(Math.round((18+o.userData.required*7)*state.multiplier));xp(11);playSound('crash');dust(o.position,14,'#e48958');scene.remove(o);showToast(`CRASH! ${o.userData.name[0].toUpperCase()+o.userData.name.slice(1)} virou confete.`);progress();}
function dust(pos,n,color){for(let i=0;i<n;i++){const m=mesh(new THREE.BoxGeometry(.13+Math.random()*.14,.13+Math.random()*.14,.13+Math.random()*.14),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1}),pos.x+(Math.random()-.5)*.5,pos.y+.3,pos.z+(Math.random()-.5)*.5);m.castShadow=false;particles.push({mesh:m,vel:new THREE.Vector3((Math.random()-.5)*4,1+Math.random()*4,(Math.random()-.5)*4),life:.45+Math.random()*.4,max:.85});}}
function shockwave(pos){const ring=mesh(new THREE.TorusGeometry(.4,.08,8,32),new THREE.MeshBasicMaterial({color:'#fff2a5',transparent:true,opacity:.9}),pos.x,.12,pos.z);ring.rotation.x=-Math.PI/2;ring.castShadow=false;const start=performance.now(),go=t=>{const p=Math.min(1,(t-start)/450);ring.scale.setScalar(1+p*9);ring.material.opacity=1-p;if(p<1)requestAnimationFrame(go);else scene.remove(ring);};requestAnimationFrame(go);}
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z);}function coins(n){state.coins+=n;}function xp(n){state.xp+=n;while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;state.multiplier=1+Math.floor(state.level/5)*.1;showToast(`NÍVEL ${state.level}! Meyui Beuyi está mais caótico.`);if(state.level%5===0)state.power++;}}
function progress(){state.missions[0].value=state.treats;state.missions[1].value=state.destroyed;state.missions[2].value=state.treasures;state.missions[3].value=state.birds;state.missions.forEach(m=>{if(m.value>=m.goal&&!m.complete){m.complete=true;coins(m.reward);showToast(`Missão concluída: +${m.reward} moedas!`);}});objective();}
function objective(){if(state.treats<30){state.region='Praia do Petisco';ui.objectiveTitle.textContent='Encontre petiscos pela Praia';ui.objectiveText.textContent='Explore o calçadão e siga o brilho dourado.';ui.objectiveProgress.textContent=`${state.treats} / 30`;ui.objectiveFill.style.width=`${state.treats/30*100}%`;}else if(state.treats<60){state.region='Ruas da Confusão';ui.objectiveTitle.textContent='Desbloqueie as ruas';ui.objectiveText.textContent='Quebre objetos e encontre 60 petiscos.';ui.objectiveProgress.textContent=`${state.treats} / 60`;ui.objectiveFill.style.width=`${state.treats/60*100}%`;}else if(state.treats<90){state.region='Centro do Caos';ui.objectiveTitle.textContent='A cidade está aberta!';ui.objectiveText.textContent='Aventure-se rumo ao Morro do Mistério.';ui.objectiveProgress.textContent=`${state.treats} / 90`;ui.objectiveFill.style.width=`${state.treats/90*100}%`;}else{state.region='Morro do Mistério';ui.objectiveTitle.textContent='O segredo da Ilha do Osso';ui.objectiveText.textContent='Faltam poucos petiscos para o final lendário.';ui.objectiveProgress.textContent=`${state.treats} / 120`;ui.objectiveFill.style.width=`${state.treats/120*100}%`;}}
function renderUpgrades(){ui.upgradeList.innerHTML=upgrades.map(u=>{const level=state.upgrades[u.id],cost=Math.round(u.base*Math.pow(1.52,level));return `<article class="upgrade-item"><span class="upgrade-icon">${u.icon}</span><div><h3>${u.title} <small>NV. ${level}</small></h3><p>${u.desc}</p></div><button data-upgrade="${u.id}" ${state.coins<cost?'disabled':''}>● ${format(cost)}</button></article>`}).join('');ui.upgradeList.querySelectorAll('button').forEach(b=>b.onclick=()=>buy(b.dataset.upgrade));}
function buy(id){const u=upgrades.find(v=>v.id===id),cost=Math.round(u.base*Math.pow(1.52,state.upgrades[id]));if(state.coins<cost)return;state.coins-=cost;state.upgrades[id]++;if(id==='force'&&state.power<state.upgrades.force)state.power=state.upgrades.force;showToast(`${u.title} melhorado! Meyui abana o rabinho.`);updateUI();renderUpgrades();}
function renderMissions(){ui.missionList.innerHTML=state.missions.map(m=>`<article class="mission-item ${m.complete?'complete':''}"><h3>${m.title}</h3><p>${m.text}</p><div class="meter"><i style="width:${Math.min(100,m.value/m.goal*100)}%"></i></div><div class="mission-meta"><span>${Math.min(m.value,m.goal)} / ${m.goal}</span><span>● ${m.reward}</span></div></article>`).join('');}
function openDrawer(id){document.querySelectorAll('.drawer').forEach(d=>d.hidden=true);if(id==='upgradeDrawer')renderUpgrades();if(id==='missionDrawer')renderMissions();$(id).hidden=false;}
function prestige(){if(state.level<20)return;state.cosmic++;state.coins=250;state.level=1;state.xp=0;state.power=1;Object.keys(state.upgrades).forEach(k=>state.upgrades[k]=0);showToast('Prestígio Canino! Biscoito Cósmico ganho.');updateUI();}
function event(){ui.eventText.textContent='CHUVA DE PETISCOS! Vá para o calçadão.';ui.eventBanner.classList.add('show');for(let i=0;i<10;i++){const c=treat(player.pos.x+(Math.random()-.5)*14,player.pos.z+(Math.random()-.5)*14,2000+i);c.position.y=1+Math.random()*3;c.userData.baseY=c.position.y;}setTimeout(()=>ui.eventBanner.classList.remove('show'),5000);}
function updateUI(){progressUI();ui.coins.textContent=format(state.coins);ui.drawerCoins.textContent=format(state.coins);ui.cosmic.textContent=state.cosmic;ui.level.textContent=state.level;ui.xpLabel.textContent=`${Math.floor(state.xp)} / ${state.level*100} XP`;ui.xpFill.style.width=`${state.xp/(state.level*100)*100}%`;ui.treats.textContent=state.treats;ui.power.textContent=state.power;ui.powerName.textContent=state.power>=10?'— postes':state.power>=5?'— bancas':'— caixas';ui.multiplier.textContent=`x${state.multiplier.toFixed(1)}`;ui.regionName.textContent=state.region;ui.weatherIcon.textContent=Math.sin(state.time*.08)>0?'☀':'☾';const p=$('prestigeButton');p.disabled=state.level<20;p.textContent=state.level>=20?'PRESTIGIAR':'INDISPONÍVEL';}
function progressUI(){state.missions[0].value=state.treats;state.missions[1].value=state.destroyed;state.missions[2].value=state.treasures;state.missions[3].value=state.birds;objective();}
function format(n){if(n>=1e12)return(n/1e12).toFixed(1)+'T';if(n>=1e9)return(n/1e9).toFixed(1)+'B';if(n>=1e6)return(n/1e6).toFixed(1)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return Math.floor(n).toString();}function showToast(text){ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2200);}
setup();
