import {DIFFICULTIES,CHAOS_LEVELS} from './run-config.js';
import {LOOT_WEAPON_BY_ID,ATTACHMENTS} from './loot-config.js';

const html=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const integer=value=>Math.max(0,Math.floor(Number(value)||0)).toLocaleString('pt-BR');
const pct=value=>`${Math.round(value*100)}%`;
const CHARACTERS={meyui:'Meyui · Equilibrado',scout:'Batedor · Movimento +4% / vida −5%',keeper:'Guardião · Vida do Faro +8% / munição −5%'};
const SKINS={default:'Original',copper:'Cobre',midnight:'Meia-noite'};
const TAGS={reload:'Recarga',survival:'Sobrevivência',critical:'Crítico',movement:'Mobilidade',ammo:'Munição',kill:'Eliminações',area:'Área',element:'Elemental',cadence:'Cadência',dog:'Faro',precision:'Precisão',damage:'Dano',risk:'Risco',supply:'Suprimentos'};
export function formatPerkDelta(perk){
  const from=Math.max(0,perk.level||0),to=from+1;
  const format={quickHands:n=>`−${n*12}% recarga`,ironSkin:n=>`+${n*18}% vida · ${n*4}% resistência`,deadeye:n=>`+${n*8}% crítico · +${n*12}% dano crítico`,lightweight:n=>`+${n*6}% movimento`,ammoHoarder:n=>`+${n*25}% reserva`,secondWind:n=>`${n} chance de levantar`,recycle:n=>`${n*5}% do pente por kill`,headburst:n=>`${n*25}% dano em área`,conductor:n=>`+${n} alvo elétrico`,catalyst:n=>`+${n*15}% dano elemental`,momentum:n=>`até +${n*20}% cadência`,bond:n=>`+${n*15}% dano Faro · −${n*7}% intervalo`,recovery:n=>`${n} vida por kill`,penetrator:n=>`+${n} alvo perfurado`,riskTaker:n=>`+${n*12}% dano · −${n*8}% vida`}[perk.id];
  return format?{before:format(from),after:format(to)}:{before:'Recompensa imediata',after:perk.description||''};
}
export function difficultyPreview(difficultyId='normal',chaosLevel=0){const difficulty=DIFFICULTIES.find(item=>item.id===difficultyId)||DIFFICULTIES[1],chaos=CHAOS_LEVELS.find(item=>item.level===Number(chaosLevel))||CHAOS_LEVELS[0];return {difficulty,chaos,reward:difficulty.reward*chaos.reward,loot:difficulty.lootChance*chaos.lootChance,health:difficulty.health*chaos.health,damage:difficulty.damage*chaos.damage};}

export function createRunUI({meta,getDirector=()=>null,experience,toast=()=>{},onChoose,onLoadout=()=>{}}){
  const $=id=>document.getElementById(id),shell=document.querySelector('.game-shell'),start=$('startScreen'),hud=$('gameHud'),abort=new AbortController(),signal=abort.signal;
  if(!shell||!start||!hud)throw new Error('Run UI requires the game shell, start menu and HUD.');
  let choices=[],choosing=false,metaTab='loadout',lastHUD='',lastBalance=-1;
  start.classList.add('run-enhanced');
  const controls=document.createElement('section');controls.id='runSetup';controls.className='run-setup';controls.setAttribute('aria-label','Configurar expedição');
  controls.innerHTML=`<div class="run-setup-heading"><span>SUA PRÓXIMA EXPEDIÇÃO</span><b id="runMapLabel">MORRO DO VENTO</b></div><div class="run-select-row"><label>Dificuldade<select id="difficultySelect" aria-describedby="difficultyDescription">${DIFFICULTIES.map(item=>`<option value="${html(item.id)}"${item.id==='normal'?' selected':''}>${html(item.name)}</option>`).join('')}</select></label><label>Indutor de Caos<select id="chaosSelect" aria-describedby="chaosDescription"></select></label></div><p class="run-difficulty-copy" id="difficultyDescription"></p><div class="run-risk-reward"><span>PETISCOS <b id="runRewardPreview">×1,00</b></span><span>LOOT <b id="runLootPreview">×1,00</b></span><span>HP INIMIGO <b id="runThreatPreview">×1,00</b></span></div><p id="chaosDescription" class="run-chaos-description" hidden></p><label class="run-weapon-select">Equipamento inicial<select id="startWeaponSelect"></select><small id="startWeaponDescription"></small></label>`;
  $('startButton').before(controls);
  const metaButton=document.createElement('button');metaButton.id='startMetaButton';metaButton.className='start-meta-button';metaButton.innerHTML='Seu legado <span>◇ <b id="startShardBalance">0</b></span>';start.querySelector('.menu-secondary').prepend(metaButton);
  const record=document.createElement('aside');record.className='run-record-strip';record.innerHTML='<span>SEU RECORDE <b id="menuBestRound">—</b></span><i></i><span>EXPEDIÇÕES <b id="menuRuns">0</b></span>';start.append(record);
  const metaScreen=document.createElement('section');metaScreen.id='metaScreen';metaScreen.className='modal-layer meta-screen';metaScreen.hidden=true;metaScreen.setAttribute('role','dialog');metaScreen.setAttribute('aria-modal','true');metaScreen.setAttribute('aria-labelledby','metaTitle');
  metaScreen.innerHTML=`<div class="modal-card meta-dialog"><header class="drawer-head"><div><span class="eyebrow">CADA EXPEDIÇÃO DEIXA UMA MARCA</span><h2 id="metaTitle">O que <em>fica.</em></h2><p>Novas possibilidades para a próxima partida.</p></div><button class="close-button" data-run-close="metaScreen" aria-label="Fechar legado">×</button></header><div class="meta-overview"><div class="meta-currency"><span aria-hidden="true">◇</span><div><small>FRAGMENTOS DE ECO</small><b id="metaBalance">0</b></div></div><p>Derrote bosses, complete desafios e alcance marcos de rounds.</p></div><nav class="meta-tabs" aria-label="Seu legado"><button data-meta-tab="loadout" aria-pressed="true">Equipamento</button><button data-meta-tab="preparation" aria-pressed="false">Preparação & Caos</button><button data-meta-tab="achievements" aria-pressed="false">Conquistas</button></nav><div id="metaContent"></div><p id="metaStatus" class="meta-status" role="status"></p><footer class="meta-footer"><span id="metaStorageStatus">Salvo neste navegador.</span><button class="resume-button" data-run-close="metaScreen">PRONTO PARA MAIS UMA →</button></footer></div>`;shell.append(metaScreen);
  const buildScreen=document.createElement('section');buildScreen.id='buildScreen';buildScreen.className='modal-layer build-screen';buildScreen.hidden=true;buildScreen.setAttribute('role','dialog');buildScreen.setAttribute('aria-modal','true');buildScreen.setAttribute('aria-labelledby','buildTitle');
  buildScreen.innerHTML=`<div class="modal-card build-dialog"><header class="build-heading"><span class="eyebrow">A PRÓXIMA SINERGIA COMEÇA AQUI</span><h2 id="buildTitle">Dê forma ao <em>caos.</em></h2><p>Escolha uma melhoria. Ela acompanha você até o fim desta partida.</p></header><div class="build-choices" id="buildChoices"></div><footer class="build-footer"><span>ESCOLHA 1 DE 3</span><span>A horda espera sua escolha.</span></footer></div>`;shell.append(buildScreen);
  const identity=document.createElement('div');identity.className='run-identity';identity.id='runIdentityHud';identity.innerHTML='<span id="runDifficultyLabel"></span><b id="runChaosBadge" hidden></b><small id="runPhaseLabel"></small>';hud.querySelector('.round-hud').append(identity);
  const powerups=document.createElement('section');powerups.className='run-active-powers';powerups.id='runActivePowerups';powerups.setAttribute('aria-label','Power-ups temporários');powerups.hidden=true;hud.append(powerups);
  const event=document.createElement('div');event.id='runEventHud';event.className='run-event-hud';event.hidden=true;event.innerHTML='<i></i><b></b><span></span>';hud.querySelector('.round-hud').append(event);
  const challengePanel=document.createElement('section');challengePanel.id='runChallenges';challengePanel.className='run-challenges';$('missionList')?.after(challengePanel);
  const listen=(element,type,callback)=>element.addEventListener(type,callback,{signal});
  listen($('difficultySelect'),'change',renderDifficulty);listen($('chaosSelect'),'change',renderDifficulty);
  listen($('startWeaponSelect'),'change',()=>{if(meta.selectLoadout({weaponId:$('startWeaponSelect').value})){onLoadout(meta.getRunBonuses());renderWeaponDescription();}});
  listen(metaButton,'click',()=>{renderMeta();experience.showModal('metaScreen');});
  listen(metaScreen,'click',event=>{
    const button=event.target.closest('button');if(!button)return;
    if(button.hasAttribute('data-run-close')){experience.closeModal();return;}
    if(button.dataset.metaTab){metaTab=button.dataset.metaTab;renderMeta();return;}
    const id=button.dataset.metaPurchase;if(!id)return;
    if(meta.purchase(id)){const name=meta.getMenuData().upgrades.find(item=>item.id===id)?.name;renderMenu();renderMeta();$('metaStatus').textContent=`${name} desbloqueado.`;toast(`${name} — disponível na próxima expedição.`);metaScreen.querySelector(`[data-meta-purchase="${id}"]`)?.focus({preventScroll:true});}
    else $('metaStatus').textContent='Você precisa de mais fragmentos para esta melhoria.';
  });
  listen(metaScreen,'change',event=>{const field=event.target.dataset.loadout;if(!field)return;const value=event.target.value||null;if(meta.selectLoadout({[field]:value})){onLoadout(meta.getRunBonuses());renderMenu();$('metaStatus').textContent='Equipamento inicial atualizado.';}});
  listen(buildScreen,'click',event=>{const button=event.target.closest('[data-build-choice]'),id=button?.dataset.buildChoice;if(!id||choosing||!choices.some(item=>item.id===id))return;choosing=true;const accepted=onChoose?onChoose(id):getDirector()?.choosePerk(id);if(accepted===false){choosing=false;return;}choices=[];choosing=false;experience.closeModal();});

  function renderDifficulty(){const preview=difficultyPreview($('difficultySelect').value,$('chaosSelect').value),factor=value=>`×${value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}`;controls.style.setProperty('--difficulty-color',preview.difficulty.color);controls.classList.toggle('chaos-selected',preview.chaos.level>0);$('difficultyDescription').textContent=preview.difficulty.description;$('runRewardPreview').textContent=factor(preview.reward);$('runLootPreview').textContent=factor(preview.loot);$('runThreatPreview').textContent=factor(preview.health);$('chaosDescription').hidden=preview.chaos.level===0;$('chaosDescription').textContent=preview.chaos.description;}
  function renderWeaponDescription(){const weapon=LOOT_WEAPON_BY_ID[$('startWeaponSelect').value];$('startWeaponDescription').textContent=weapon?`${weapon.category} · ${weapon.magazineSize} no pente · ${weapon.description}`:'';}
  function renderMenu(){
    const data=meta.getMenuData(),selected=$('chaosSelect').value||'0';$('chaosSelect').innerHTML=CHAOS_LEVELS.map(level=>`<option value="${level.level}"${level.level>data.maxChaos?' disabled':''}>${html(level.name)}${level.level>data.maxChaos?' · bloqueado':''}</option>`).join('');$('chaosSelect').value=Number(selected)<=data.maxChaos?selected:'0';
    $('startWeaponSelect').innerHTML=data.options.weaponIds.filter(id=>LOOT_WEAPON_BY_ID[id]).map(id=>`<option value="${id}">${html(LOOT_WEAPON_BY_ID[id].name)}</option>`).join('');$('startWeaponSelect').value=data.loadout.weaponId;$('startShardBalance').textContent=integer(data.shards);$('menuBestRound').textContent=data.stats.bestRound?`ROUND ${integer(data.stats.bestRound)}`:'SUA PRIMEIRA HISTÓRIA';$('menuRuns').textContent=integer(data.stats.runs);lastBalance=data.shards;
    const director=getDirector(),started=!!director&&director.phase!=='ready';for(const id of ['difficultySelect','chaosSelect','startWeaponSelect'])$(id).disabled=started;
    if(started){$('difficultySelect').value=director.difficulty;$('chaosSelect').value=String(director.chaos);}
    controls.querySelector('.run-setup-heading>span').textContent=started?'EXPEDIÇÃO EM ANDAMENTO':'SUA PRÓXIMA EXPEDIÇÃO';renderDifficulty();renderWeaponDescription();
  }
  function upgradeDelta(upgrade){const current=upgrade.level,next=Math.min(upgrade.max,current+1);if(upgrade.id==='supplies')return `${100+current*10}% → ${100+next*10}% munição inicial`;if(upgrade.id==='conditioning')return `${100+current*5}% → ${100+next*5}% vida inicial`;if(upgrade.id==='companion')return `${100+current*10}% → ${100+next*10}% vida do Faro`;if(upgrade.id==='chaos')return `CHAOS ${current+1} → CHAOS ${next+1}`;return upgrade.owned?'LIBERADO PARA SEU EQUIPAMENTO':'NOVA OPÇÃO DE EQUIPAMENTO';}
  function renderMeta(){
    const data=meta.getMenuData();$('metaBalance').textContent=integer(data.shards);$('metaStorageStatus').textContent=data.storageAvailable?'Seu legado fica salvo neste navegador.':'Seu legado está disponível nesta sessão.';metaScreen.querySelectorAll('[data-meta-tab]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.metaTab===metaTab)));
    if(metaTab==='achievements'){$('metaContent').innerHTML=`<div class="meta-achievement-grid">${data.achievements.map(item=>`<article class="meta-achievement ${item.complete?'complete':''}"><span class="meta-achievement-symbol">${item.complete?'✦':'◇'}</span><div><h3>${html(item.name)}</h3><p>${html(item.description)}</p><div class="meta-progress"><i style="width:${pct(item.progress/item.target)}"></i></div><small>${integer(item.progress)} / ${integer(item.target)}</small></div><b>${item.complete?'CONCLUÍDA':`◇ ${item.shards}`}</b></article>`).join('')}</div>`;return;}
    const upgrades=data.upgrades.filter(item=>metaTab==='preparation'?['preparation','challenge'].includes(item.branch):!['preparation','challenge'].includes(item.branch));
    const select=(field,label,values,names)=>`<label>${label}<select data-loadout="${field}">${field==='attachmentId'?'<option value="">Sem acessório inicial</option>':''}${values.map(id=>`<option value="${html(id)}"${data.loadout[field]===id?' selected':''}>${html(names[id]||id)}</option>`).join('')}</select></label>`;
    const loadout=metaTab==='loadout'?`<section class="meta-loadout"><div><span class="eyebrow">EQUIPAMENTO DA PRÓXIMA PARTIDA</span><p>Escolha entre as opções que você já liberou.</p></div><div class="meta-loadout-grid">${select('weaponId','Arma inicial',data.options.weaponIds,Object.fromEntries(Object.entries(LOOT_WEAPON_BY_ID).map(([id,weapon])=>[id,weapon.name])))}${select('attachmentId','Acessório inicial',data.options.attachmentIds,Object.fromEntries(Object.entries(ATTACHMENTS).map(([id,item])=>[id,item.name])))}${select('character','Especialização',data.options.characters,CHARACTERS)}${select('skin','Equipamento do Faro',data.options.skins,SKINS)}</div></section>`:'';
    $('metaContent').innerHTML=`${loadout}<div class="meta-upgrade-grid">${upgrades.map(item=>`<article class="meta-upgrade ${item.owned?'owned':''}"><div class="meta-upgrade-top"><span>${html(item.branch==='challenge'?'RISCO & RECOMPENSA':item.branch==='preparation'?'PREPARAÇÃO':item.branch==='cosmetic'?'VISUAL':'NOVA POSSIBILIDADE')}</span><b>${item.level} / ${item.max}</b></div><h3>${html(item.name)}</h3><p>${html(item.description)}</p><div class="meta-upgrade-delta">${html(upgradeDelta(item))}</div><button data-meta-purchase="${item.id}"${item.owned||data.shards<item.cost?' disabled':''}>${item.owned?'DESBLOQUEADO':`DESBLOQUEAR <b>◇ ${item.cost}</b>`}</button></article>`).join('')}</div>`;
  }
  function showChoices(nextChoices){choices=(Array.isArray(nextChoices)?nextChoices:[]).filter(choice=>choice?.id).slice(0,3);if(!choices.length)return false;choosing=false;$('buildChoices').innerHTML=choices.map((choice,index)=>{const delta=formatPerkDelta(choice);return `<button class="build-choice" data-build-choice="${html(choice.id)}" style="--choice-index:${index}"><div class="build-choice-top"><span>0${index+1}</span><small>${choice.level?'EVOLUIR SINERGIA':'NOVA POSSIBILIDADE'}</small></div><span class="build-icon" aria-hidden="true">${html(choice.icon||'✦')}</span><div class="build-tags">${(choice.tags||[]).slice(0,2).map(tag=>`<span>${html(TAGS[tag]||tag)}</span>`).join('')}</div><h3>${html(choice.name)}</h3><p>${html(choice.description)}</p><div class="build-delta"><span>${html(delta.before)}</span><i>↓</i><b>${html(delta.after)}</b></div><div class="build-select-label">ESCOLHER <span>↗</span></div></button>`;}).join('');experience.showModal('buildScreen');return true;}
  function renderChallenges(){const data=meta.getMenuData();challengePanel.innerHTML=`<div class="run-challenge-heading"><span class="eyebrow">DESAFIOS DESTA EXPEDIÇÃO</span><span>RECOMPENSA PERMANENTE</span></div>${data.challenges.map(item=>`<article class="run-challenge ${item.complete?'complete':''}"><div><b>${html(item.name)}</b><p>${html(item.description)}</p><small>${item.progress} / ${item.target}</small><div class="meta-progress"><i style="width:${pct(item.progress/item.target)}"></i></div></div><span>${item.complete?'✓':`◇ ${item.shards}`}</span></article>`).join('')}`;}
  function update(value=getDirector()?.getHUD()){
    if(meta.state.shards!==lastBalance){lastBalance=meta.state.shards;$('startShardBalance').textContent=integer(lastBalance);if(!metaScreen.hidden)renderMeta();}
    if(!value)return;const identityKey=JSON.stringify([value.difficulty,value.chaos,value.phase,value.countdown,value.activePowerups,value.event]);if(identityKey===lastHUD)return;lastHUD=identityKey;
    $('runDifficultyLabel').textContent=value.difficultyName||DIFFICULTIES.find(item=>item.id===value.difficulty)?.name||'Normal';$('runChaosBadge').hidden=!value.chaos;$('runChaosBadge').textContent=value.chaosName||`CHAOS ${value.chaos}`;identity.classList.toggle('chaos-active',!!value.chaos);
    $('runPhaseLabel').textContent=value.phase==='intermission'?`RESPIRO · ${value.countdown}s`:value.phase==='preparation'?`PREPARAÇÃO · ${value.countdown}s`:value.phase==='choice'?'ESCOLHA SUA EVOLUÇÃO':'';
    const active=value.activePowerups||[];powerups.hidden=!active.length;powerups.innerHTML=active.map(item=>`<div class="run-active-power" style="--power-color:${html(item.color||'#efbb66')}" title="${html(item.name)}: ${Math.ceil(item.time)} segundos"><span>${html(item.icon||'✦')}</span><div><b>${html(item.name)}</b><small>${Math.ceil(item.time)}s</small></div><i style="width:${pct(Math.max(0,Math.min(1,item.time/item.duration)))}"></i></div>`).join('');
    event.hidden=!value.event;if(value.event){event.style.setProperty('--event-color',value.event.color||'#efbb66');event.querySelector('b').textContent=value.event.name;event.querySelector('span').textContent=`${Math.ceil(value.event.time)}s`;}
  }
  renderMenu();renderChallenges();
  return {renderMenu,renderMeta,showChoices,update,renderChallenges,get pendingChoice(){return choices.length>0;},dispose(){abort.abort();controls.remove();metaButton.remove();record.remove();metaScreen.remove();buildScreen.remove();identity.remove();powerups.remove();event.remove();challengePanel.remove();start.classList.remove('run-enhanced');}};
}
